import Foundation

// The full prompt bank, split by category for readability. `PromptBank.all` (in PromptBank.swift)
// concatenates all of these. Every prompt here is answerable by anyone in ~60 seconds with no
// research, and is phrased as a direct question or instruction.

extension PromptBank {
    static let all: [SpeakingPrompt] =
        interviewPrompts + opinionPrompts + personalPrompts + hypotheticalPrompts +
        explainPrompts + storytellingPrompts + businessPrompts + abstractPrompts + funPrompts

    // MARK: - Interview

    static let interviewPrompts: [SpeakingPrompt] = [
        "Tell me about yourself.",
        "What is your greatest weakness?",
        "What is your greatest strength?",
        "Tell me about a time you failed and what you learned from it.",
        "Describe a time you handled a conflict with a coworker.",
        "Tell me about a time you led a team without having formal authority.",
        "Describe a time you missed a deadline. What happened?",
        "Tell me about a time you disagreed with your manager.",
        "Describe a mistake you made at work and how you fixed it.",
        "Why do you want this role?",
        "Where do you see yourself in five years?",
        "How do you handle working under pressure?",
        "Tell me about a project you're especially proud of.",
        "Can you explain a gap in your résumé or work history?",
        "How do you prioritize when you have multiple deadlines?",
        "What motivates you at work?",
        "Describe your ideal team to work with.",
        "Why should we hire you?",
        "Tell me about a time you went above and beyond for a customer or client.",
        "Describe a time you had to learn something new quickly for a job.",
        "How do you handle constructive criticism?",
        "Tell me about a time you had to persuade someone to see things your way.",
        "What's a professional accomplishment you're most proud of?",
        "Describe a time you had to work closely with someone difficult.",
        "How would your previous manager describe you?",
        "Tell me about a time you took initiative without being asked.",
        "What's the biggest risk you've taken in your career?",
        "Describe a time you had to give someone difficult feedback.",
        "How do you handle ambiguity when instructions aren't clear?",
        "Tell me about a goal you set for yourself and how you achieved it.",
        "What would you do in your first ninety days in this role?",
        "Describe a time you had to make a decision without all the information you wanted.",
        "Tell me about a time you managed competing priorities under a tight deadline.",
        "What's a professional skill you're actively working to develop right now?",
        "Describe a time you turned around a project that was struggling.",
        "Tell me about a time you had to say no to a request at work.",
        "Why are you looking to leave your current job?",
        "Tell me about a time you had to quickly earn a new team's trust.",
    ].map { SpeakingPrompt(text: $0, category: .interview) }

    // MARK: - Opinion (debatable, not divisive)

    static let opinionPrompts: [SpeakingPrompt] = [
        "Should homework be abolished in schools?",
        "Is remote work better than working in an office?",
        "Are cover letters still useful in job applications?",
        "Should college be free for everyone?",
        "Is a four-day work week better for productivity?",
        "Should tipping be replaced with higher menu prices?",
        "Are open floor-plan offices good or bad for productivity?",
        "Should students be required to learn a second language?",
        "Is social media doing more harm than good?",
        "Should salary ranges be required in every job posting?",
        "Is it better to specialize in one skill or be a generalist?",
        "Should standardized testing matter less in college admissions?",
        "Are annual performance reviews actually useful?",
        "Should companies let employees work from anywhere in the world?",
        "Is it better to rent or buy a home in your twenties?",
        "Should smartphones be banned in classrooms?",
        "Is competition healthier than collaboration for getting results?",
        "Should there be a minimum required amount of vacation time?",
        "Is it better to job-hop or stay loyal to one company?",
        "Should schools teach personal finance as a required course?",
        "Are unpaid internships fair to entry-level candidates?",
        "Should meetings that could be an email be banned?",
        "Should companies be allowed to monitor employees' computer activity?",
        "Is streaming better than owning physical movies and music?",
        "Should artificial intelligence be used to grade student work?",
        "Is it better to live in a big city or a small town?",
        "Should employees be required to use their full vacation days?",
        "Is a college degree still necessary to succeed in most careers?",
        "Should fast fashion be discouraged in favor of buying less, higher-quality clothing?",
        "Is it better to save aggressively or enjoy your money now?",
        "Should there be a cap on how many hours someone can work in a week?",
        "Is texting a worse way to communicate than calling?",
        "Should employers be allowed to ask about salary history during interviews?",
        "Is it healthier to follow a strict routine or stay spontaneous?",
        "Should public transportation be free in major cities?",
        "Is it better to have many casual friends or a few close ones?",
        "Should companies give employees equity instead of year-end bonuses?",
    ].map { SpeakingPrompt(text: $0, category: .opinion) }

    // MARK: - Personal

    static let personalPrompts: [SpeakingPrompt] = [
        "Describe your perfect Saturday.",
        "What's a hobby you wish you had more time for?",
        "What's the best piece of advice you've ever received?",
        "Describe the person who has influenced you the most.",
        "What's a small habit that's made a big difference in your life?",
        "What does success mean to you personally?",
        "Describe a place that feels like home to you.",
        "What's something you've changed your mind about recently?",
        "What's a book, show, or movie that stuck with you, and why?",
        "Describe a challenge you overcame that made you stronger.",
        "What's your favorite way to unwind after a stressful day?",
        "What's a tradition from your family or culture that matters to you?",
        "Describe a moment you felt truly proud of yourself.",
        "What's something you're currently trying to get better at?",
        "Who is someone you admire, and why?",
        "What's a risk you took that paid off?",
        "Describe your morning routine.",
        "What's the most memorable trip you've taken?",
        "What's a fear you've worked to overcome?",
        "Describe a friendship that has shaped who you are.",
        "What's something you do differently now than you did five years ago?",
        "What's a compliment you received that you still remember?",
        "Describe a time someone showed you unexpected kindness.",
        "What's your favorite way to spend time with family?",
        "What's a lesson your parents or guardians taught you?",
        "Describe your relationship with your phone or social media.",
        "What's something that always makes you laugh?",
        "What's a goal you're currently working toward outside of work?",
        "Describe how you handle stress.",
        "What's a skill you taught yourself?",
        "What's the last thing that made you genuinely happy?",
        "Describe a decision you're glad you made.",
        "What does a good work-life balance look like for you?",
        "What's something about yourself that surprises people?",
        "Describe how you like to celebrate your wins.",
        "What's a piece of advice you'd give your younger self?",
    ].map { SpeakingPrompt(text: $0, category: .personal) }

    // MARK: - Hypothetical

    static let hypotheticalPrompts: [SpeakingPrompt] = [
        "If you could master any skill overnight, what would it be?",
        "If you had an extra hour every day, how would you use it?",
        "If you could have dinner with anyone, living or dead, who would it be?",
        "If you won a million dollars tomorrow, what's the first thing you'd do?",
        "If you could live in any decade, which would you pick?",
        "If you had to move to a new city tomorrow, where would you go?",
        "If you could instantly become fluent in another language, which would you choose?",
        "If you could swap jobs with anyone for a day, whose job would you want?",
        "If you could only eat one cuisine for the rest of your life, what would it be?",
        "If you could give everyone in the world one piece of advice, what would it be?",
        "If you had to teach a class on any topic tomorrow, what would you teach?",
        "If you could remove one household chore from your life forever, which would it be?",
        "If you could travel anywhere right now, with no cost involved, where would you go?",
        "If you could redesign your daily commute, what would it look like?",
        "If you had to start a business tomorrow with no money, what would you do?",
        "If you could relive one year of your life, which would you choose?",
        "If you could add one rule everyone had to follow, what would it be?",
        "If your life were a movie, what genre would it be?",
        "If you could trade places with a fictional character for a week, who would you choose?",
        "If you could only keep five possessions, what would they be?",
        "If you had to survive a year on a deserted island, what three things would you bring?",
        "If you could ask a future version of yourself one question, what would you ask?",
        "If you could change one thing about how you were raised, what would it be?",
        "If you could instantly gain a year of experience in any skill, what would you pick?",
        "If you had to give up your phone for a month, what would you miss most?",
        "If you could design your ideal workday from scratch, what would it look like?",
        "If you could time travel to witness one historical event, which would you choose?",
        "If you could have any superpower for a single day, what would you do with it?",
        "If you had to convince a stranger to try your favorite hobby, what would you say?",
        "If you could erase one worry from your mind permanently, which would it be?",
        "If you could pick any mentor, real or fictional, who would guide you?",
        "If your favorite meal disappeared from existence, what would you eat instead?",
        "If you had to switch careers completely, what would you do instead?",
        "If you could invent a new holiday, what would it celebrate?",
        "If you could live without one modern convenience, what would you give up?",
        "If you could relive your favorite birthday, which one would it be?",
    ].map { SpeakingPrompt(text: $0, category: .hypothetical) }

    // MARK: - Explain It

    static let explainPrompts: [SpeakingPrompt] = [
        "Explain how compound interest works.",
        "Explain how a vaccine works.",
        "Explain why the sky is blue.",
        "Explain how GPS determines your location.",
        "Explain what an API is.",
        "Explain how a credit score is calculated.",
        "Explain how the stock market works.",
        "Explain how Wi-Fi lets your phone connect to the internet.",
        "Explain what inflation is and why it happens.",
        "Explain how a search engine finds results.",
        "Explain the difference between weather and climate.",
        "Explain how airplanes stay in the air.",
        "Explain what blockchain is.",
        "Explain how your immune system fights off a cold.",
        "Explain what compound annual growth rate means.",
        "Explain how an interest rate affects what you pay back on a loan.",
        "Explain what machine learning is.",
        "Explain how a refrigerator keeps food cold.",
        "Explain what a recession is.",
        "Explain how solar panels generate electricity.",
        "Explain what cryptocurrency is.",
        "Explain how taxes are calculated on a paycheck.",
        "Explain what a mortgage is.",
        "Explain how noise-canceling headphones work.",
        "Explain what net neutrality means.",
        "Explain how a car engine converts fuel into motion.",
        "Explain what a firewall does to protect a computer.",
        "Explain how time zones work.",
        "Explain what supply and demand means.",
        "Explain how a microwave heats food.",
        "Explain what the placebo effect is.",
        "Explain how your body builds muscle from exercise.",
        "Explain what a 401(k) is.",
        "Explain how photosynthesis works.",
        "Explain what an algorithm is.",
        "Explain how earthquakes happen.",
        "Explain what emotional intelligence means.",
        "Explain how a thermostat keeps a room at a set temperature.",
    ].map { SpeakingPrompt(text: $0, category: .explain) }

    // MARK: - Storytelling

    static let storytellingPrompts: [SpeakingPrompt] = [
        "Tell the story of your first job.",
        "Tell the story of how you met your best friend.",
        "Tell the story of a trip that didn't go as planned.",
        "Tell the story of a time you got lost.",
        "Tell the story of your favorite childhood memory.",
        "Tell the story of a time you tried something completely new.",
        "Tell the story of the last time you laughed until it hurt.",
        "Tell the story of a gift you'll never forget.",
        "Tell the story of how you chose your career path.",
        "Tell the story of a time you had to think on your feet.",
        "Tell the story of the best meal you've ever had.",
        "Tell the story of a time you helped a stranger.",
        "Tell the story of your most memorable birthday.",
        "Tell the story of a time you were completely surprised.",
        "Tell the story of how you learned to ride a bike, drive, or swim.",
        "Tell the story of a time you overcame stage fright or nerves.",
        "Tell the story of a competition you took part in.",
        "Tell the story of a time plans fell through at the last minute.",
        "Tell the story of your first day at a new school or job.",
        "Tell the story of the last vacation you took.",
        "Tell the story of a time you had to apologize to someone.",
        "Tell the story of a pet that means or meant a lot to you.",
        "Tell the story of a time you got some unexpected good news.",
        "Tell the story of a time you performed in front of an audience.",
        "Tell the story of the moment you decided to make a big change in your life.",
        "Tell the story of a time you worked as part of a team to solve a problem.",
        "Tell the story of a mistake that turned into a funny memory.",
        "Tell the story of how you spent a recent holiday.",
        "Tell the story of a time you had to stand up for yourself.",
        "Tell the story of the last time you tried a new restaurant or dish.",
        "Tell the story of a time technology failed you at the worst moment.",
        "Tell the story of how you picked the city or neighborhood you live in.",
        "Tell the story of a project you built from scratch.",
        "Tell the story of a time someone gave you great advice right when you needed it.",
        "Tell the story of the last time you moved somewhere new.",
        "Tell the story of a time you had to improvise a speech or toast.",
    ].map { SpeakingPrompt(text: $0, category: .storytelling) }

    // MARK: - Business & Tech

    static let businessPrompts: [SpeakingPrompt] = [
        "Pitch a product that solves a problem you had this week.",
        "What's one feature you'd add to your favorite app?",
        "Pitch a business idea based on something you wish existed.",
        "How would you explain your job to someone with no industry background?",
        "What's a company you admire, and what makes their strategy work?",
        "If you were the CEO of your company for a day, what's the first thing you'd change?",
        "Pitch an improvement to a product you use every day.",
        "What's a startup idea you think could actually work?",
        "How would you convince a customer to switch from a competitor to your product?",
        "What's one inefficiency at your workplace you'd fix if you could?",
        "How would you market a product to a completely new audience?",
        "What's a skill every entrepreneur needs, and why?",
        "If you had to cut your company's budget by twenty percent, what would you cut first?",
        "What's a piece of technology you think is overrated?",
        "What's a piece of technology you think is underrated?",
        "How would you pitch your résumé as a product to a hiring manager?",
        "What's a business that struggled because it ignored its customers?",
        "How should a small business decide whether to raise its prices?",
        "What's one way artificial intelligence could improve your current job?",
        "How would you design the onboarding experience for a brand-new employee?",
        "What's a subscription service you think is worth the money, and why?",
        "How would you pitch a fundraiser for a cause you care about?",
        "What's the biggest risk in launching a product too early?",
        "How would you handle a customer who's furious about a mistake your company made?",
        "What's one lesson from sports or games that applies to running a business?",
        "If your team had to ship a project in half the usual time, what would you cut?",
        "What's a product you bought recently that exceeded your expectations?",
        "How do you decide whether a new tool or app is actually worth adopting?",
        "What's a way small businesses can compete with large corporations?",
        "How would you pitch remote work to a manager who prefers everyone in-office?",
        "What's a red flag you look for when evaluating a company to work for?",
        "How would you explain the value of good design to someone who doesn't see the point?",
        "What's one way social media has changed how businesses reach customers?",
        "If you were building an app from scratch, what problem would it solve?",
        "What's a negotiation tactic you think works well?",
        "How would you build trust with a client on a project that's behind schedule?",
    ].map { SpeakingPrompt(text: $0, category: .business) }

    // MARK: - Big Ideas (abstract)

    static let abstractPrompts: [SpeakingPrompt] = [
        "What does it mean to be successful?",
        "Is it better to be respected or liked?",
        "What makes a good leader?",
        "Is happiness something you find or something you create?",
        "What does it mean to live a meaningful life?",
        "What does it mean to deserve success?",
        "What role does failure play in growth?",
        "Is intelligence more valuable than emotional awareness?",
        "What does true confidence look like?",
        "Is it better to take risks or play it safe?",
        "What does freedom really mean to you?",
        "Is ambition always a good thing?",
        "What separates a good idea from a great one?",
        "Is it more important to be consistent or to be adaptable?",
        "What does integrity mean in everyday life?",
        "Is competition necessary for progress?",
        "What makes someone trustworthy?",
        "Is it better to have many options or one clear path?",
        "What does courage look like in ordinary, everyday moments?",
        "Is patience a strength or sometimes a weakness?",
        "What's the difference between confidence and arrogance?",
        "Is it better to lead by example or by instruction?",
        "What does it mean to truly listen to someone?",
        "Is perfection a useful goal or a trap?",
        "What makes a decision the right one?",
        "Is it better to focus on your strengths or fix your weaknesses?",
        "What does resilience actually look like in practice?",
        "Is it possible to be too honest?",
        "What does it mean to be authentic?",
        "Is it better to plan carefully or stay flexible?",
        "What separates a habit from a routine?",
        "Is curiosity more valuable than discipline?",
        "What does it take to change someone's mind?",
        "Is it better to be early and wrong or late and right?",
        "What makes work feel meaningful rather than just a job?",
        "Is comfort the enemy of growth?",
    ].map { SpeakingPrompt(text: $0, category: .abstract) }

    // MARK: - Just for Fun

    static let funPrompts: [SpeakingPrompt] = [
        "What's the most overrated food, and why?",
        "If animals could talk, which would be the rudest?",
        "What's your most useless talent?",
        "If you had a theme song that played whenever you entered a room, what would it be?",
        "What's the weirdest food combination you actually enjoy?",
        "If you could instantly be a world champion at any sport, which would you pick?",
        "What's a trend you're glad is over?",
        "If you had to be a kitchen appliance, which one would you be?",
        "What's the funniest nickname you've ever had?",
        "If you could only communicate in movie quotes for a day, would you survive?",
        "What's your go-to karaoke song?",
        "If your pet could talk for one day, what do you think it would say?",
        "What's the most ridiculous thing you've ever bought?",
        "If you were a flavor of ice cream, which one would you be and why?",
        "What's a food you refuse to eat, no matter what?",
        "If you could banish one chore from existence, what would it be?",
        "What's the best costume you've ever worn?",
        "If you had to survive on one snack forever, what would you pick?",
        "What's a guilty pleasure you're not embarrassed to admit?",
        "If you could have any animal as a pet, regardless of practicality, what would it be?",
        "What's the most fun you've had getting lost somewhere?",
        "If you were the mascot for your own life, what would you look like?",
        "What's a silly fear you have that you know isn't rational?",
        "If you had to describe yourself using only emojis, which would you pick?",
        "What's the best prank you've ever pulled or had pulled on you?",
        "If you could add one new rule to a classic board game, what would it be?",
        "What's your most controversial food opinion?",
        "What's the silliest thing you've ever argued with someone about?",
        "What's the best souvenir you've ever brought back from somewhere?",
        "If you had a personal theme park, what would the main attraction be?",
        "What's a movie you can quote from start to finish?",
        "If you could only wear one outfit for the rest of your life, what would it be?",
        "What's the strangest talent you wish you had?",
        "If you had to invent a new sport, what would the rules be?",
        "What's your go-to dance move?",
        "If you could relive one video game level or arcade memory, which would it be?",
    ].map { SpeakingPrompt(text: $0, category: .fun) }
}
